### ISSUE TITLE
token refresh route

### ISSUE THREAD

**Issue by dpbuzz** [firebase/php-jwt#119]
I am developing an api with slim using tuupola/slim-jwt-auth to be used from smartphones.
I can't recover the payload from a expired jwt, because exeption ExpiredToken is thrown when using decode(). I want to verify the jwt and if ok, recover the payload (it has usr_id and psw_time that I use to check usr status / psw change before new token).
Any suggestion to do this?
Thanks

**Comment by dpbuzz** [comment]
Yes I see that issue... 
I finallly use the following code. I want the JWT:verify function to validate the token, and it is done before the exception.

try {
        $payload = JWT::decode($jwt ,$jwt_secret ,array('HS512'));
    }catch ( \Firebase\JWT\ExpiredException $e ) {
        // at this point the jwt was validated ok
        list($headb64, $bodyb64, $cryptob64) = explode('.', $jwt);
        $payload = base64_decode($bodyb64);
    }catch ( \Exception $e ){
        echo 'Exception message '.$e ;
    }

**Comment by psignoret** [comment]
An expired JWT should simply be considered invalid, and the contents should not be used or trusted at all. From https://tools.ietf.org/html/rfc7519#section-4.1.4:

````
  4.1.4.  "exp" (Expiration Time) Claim

   The "exp" (expiration time) claim identifies the expiration time on
   or after which the JWT MUST NOT be accepted for processing.  The
   processing of the "exp" claim requires that the current date/time
   MUST be before the expiration date/time listed in the "exp" claim.
````

In your example above, you're not technically validating the token, you're just verifying the signature (and `iat` and `nbf` claims), and *this is just a result of the order in which this library happens to do those checks*. To consider the token "valid", the `exp` claim, if provided, MUST refer to a time in the future. 

Consider, for example, a future when you changed to a different JWT library which happens to check the `exp` claim _before_ checking the signature (which is, as far as I can tell, a perfectly valid approach). A malicious client would then be able to send you an expired JWT with an invalid signature, and you would still trust your `usr_id` and `psw_time` claims, possibly granting them access to something they should have access to).

In OAuth 2.0 (as an example, though of course you may not be implementing OAuth 2.0), refreshing access tokens is done with a separate, longer-lived token (the refresh token). From https://tools.ietf.org/html/rfc6749#section-1.5:

```
1.5.  Refresh Token

   Refresh tokens are credentials used to obtain access tokens.  Refresh
   tokens are issued to the client by the authorization server and are
   used to obtain a new access token when the current access token
   becomes invalid or expires [...]
```

When the client first gets an access token, the authorization server will respond with the access token, the amount of time this token is valid, and a refresh token. This way, the client application knows how long it can use the access token (after which it will need to use the refresh token to get a new access token):

```
5.1.  Successful Response

   The authorization server issues an access token and optional refresh
   token, and constructs the response by adding the following parameters
   to the entity-body of the HTTP response with a 200 (OK) status code:

   access_token
         REQUIRED.  The access token issued by the authorization server.

   [...]

   expires_in
         RECOMMENDED.  The lifetime in seconds of the access token.  For
         example, the value "3600" denotes that the access token will
         expire in one hour from the time the response was generated.
         If omitted, the authorization server SHOULD provide the
         expiration time via other means or document the default value.

   refresh_token
         OPTIONAL.  The refresh token, which can be used to obtain new
         access tokens using the same authorization grant as described
         in Section 6.
  [...]
```

**Comment by dpbuzz** [comment]
Thank you for taking the time for the explanation.
I agree with the example you give and is true that in the future that order may change.
The original question was how to avoid user re-login when just jwt expires? ... I needed to recover usr_id from payload (this can't be done) to check against a db if it is ok and generate another jwt.   
At this point I realize that the only way is to increase exp value (for example 12hs) so the user will have to login on the smartphone once a day.

**Comment by ShivPandey** [comment]
> An expired JWT should simply be considered invalid, and the contents should not be used or trusted at all. From https://tools.ietf.org/html/rfc7519#section-4.1.4:
> 
> ```
>   4.1.4.  "exp" (Expiration Time) Claim
> 
>    The "exp" (expiration time) claim identifies the expiration time on
>    or after which the JWT MUST NOT be accepted for processing.  The
>    processing of the "exp" claim requires that the current date/time
>    MUST be before the expiration date/time listed in the "exp" claim.
> ```
> 
> In your example above, you're not technically validating the token, you're just verifying the signature (and `iat` and `nbf` claims), and **this is only a result of the order in which this library _happens_ to do those checks**. To consider the token "valid", the `exp` claim, if provided, MUST refer to a time in the future.
> 
> Consider, for example, a future when you changed to a different JWT library which happens to check the `exp` claim _before_ checking the signature (which is, as far as I can tell, a perfectly valid approach). A malicious client would then be able to send you an expired JWT with an invalid signature, and you would still trust your `usr_id` and `psw_time` claims, possibly granting them access to something they should not have access to).
> 
> In OAuth 2.0 (as an example, though of course you may not be implementing OAuth 2.0), refreshing access tokens is done with a separate, longer-lived token (the refresh token). From https://tools.ietf.org/html/rfc6749#section-1.5:
> 
> ```
> 1.5.  Refresh Token
> 
>    Refresh tokens are credentials used to obtain access tokens.  Refresh
>    tokens are issued to the client by the authorization server and are
>    used to obtain a new access token when the current access token
>    becomes invalid or expires [...]
> ```
> 
> When the client first gets an access token, the authorization server will respond with the access token, the amount of time this token is valid, and a refresh token. This way, the client application knows how long it can use the access token (after which it will need to use the refresh token to get a new access token):
> 
> ```
> 5.1.  Successful Response
> 
>    The authorization server issues an access token and optional refresh
>    token, and constructs the response by adding the following parameters
>    to the entity-body of the HTTP response with a 200 (OK) status code:
> 
>    access_token
>          REQUIRED.  The access token issued by the authorization server.
> 
>    [...]
> 
>    expires_in
>          RECOMMENDED.  The lifetime in seconds of the access token.  For
>          example, the value "3600" denotes that the access token will
>          expire in one hour from the time the response was generated.
>          If omitted, the authorization server SHOULD provide the
>          expiration time via other means or document the default value.
> 
>    refresh_token
>          OPTIONAL.  The refresh token, which can be used to obtain new
>          access tokens using the same authorization grant as described
>          in Section 6.
>   [...]
> ```

what information are stored in refresh_token and how to get access_token through refresh_token.

**Comment by cottton** [comment]
@dpbuzz its years later, i know. But you did not understand how jwt works, i guess.

@ShivPandey the refresh token contains nothing. 
A refresh token is a random unique string which is valid only once.

@ both

**Login:**
- client sends login request
- server validates request -> login valid -> logged in
- server creates new refresh_token (life time f.e. 6 hours)
- server stores the refresh token local _(combi: refresh_token => user_id)_
- server creates new access_token (life time f.e. 30 mins)
- _server does NOT store the access_token_
- server returns both token to user

...

- client receives both token
- client stores both token

...

**Request:**
- client requests server with access_token
- server validates access_token -> valid
- server completes request and returns result

... _(40 min later)_

- client request server with access_token
- server validates access_token -> invalid (expired)
- server response: request denied (401 Unauthorized)

**Refresh:**
- client sends refresh request with refresh_token
- server loads (searches) the refresh token -> found|exists _(so basically valid)_
- server checks if refresh token is still valid and not expired -> valid _(in example we set to 6 hours)_
- server _(remember: stored refresh_token => user_id)_ checks if user behind user_id is still valid
- _in example user exists and is not deleted or disabled ect_ 
- server deletes the refresh_token (one time use only!)
_Note: Following is the same as if user logs in:_
- server creates new refresh_token (life time f.e. 6 hours)
- server stores the refresh token local _(combi: refresh_token => user_id)_
- server creates new access_token (life time f.e. 30 mins)
- _server does NOT store the access_token_
- server returns both token to user

... _(2 days later)_

**Access and Refresh Token expired:**
- client requests server with **access_token**
- server validates access_token -> **invalid** (expired)
- server response: request denied (401 Unauthorized)
- client sends refresh request with **refresh_token**
- server loads (searches) the refresh token -> found|exists _(so basically valid)_
- server checks if refresh token is still valid -> **invalid** (expired)
- server response: request denied (401 Unauthorized)
- client send login request _see above_

_Client ofc can check if the token are already expired to prevent useless calls._

**Comment by dpbuzz** [comment]
Thank you both for the explanation, finally I implement the refresh token as describe on last post... I understood how it work after further reading.

**Comment by usb248** [comment]
@cottton  when you say "server stores the refresh token local ", how/where you store this jwt ?
What do you mean by "(combi: refresh_token => user_id)" ?

**Comment by cottton** [comment]
> @cottton when you say "server stores the refresh token local ", how/where you store this jwt ?

Wait! 
**JWT (JsonWebToken) !== Refesh token.**
The Refesh token is a unique (uuid) string. 
The JWT (access token) contains payload and a signature.

Server does NOT store the JWT (access token). 
_Thats the job of the client. He has to keep it and show it to other services to gain access._

Server DOES store the refresh token.
_Server needs to know who is related to the refresh token (user_id f.e.)
and if the refresh token is still valid._  

**Where:**
I would recommend to store the refresh token in a local _(only accessible from your server)_ cache.
Lets say the refresh token would be valid 20 minutes.
You then could easy save the refresh token in the cache using this 20 min as ttl (time to live).
_So the cache handles the ttl for you. But ofc you could write something else for that._

---
> What do you mean by "(combi: refresh_token => user_id)" ?

You save the combination (or should i say relation?) 
of **refresh_token** and **user_id**.

This is to identify the user (client) that is making the refresh-request.
You get a GET request with a token. The user (client) may not know which user_id he got on the auth server.
The client just knows: _"i got an expired access token (JWT). I need to use my refresh token on that url to receive a new pair of refresh- and access token"._

So the server searches _(in example in the mentioned cache above)_ for the refresh token. 
If found, then the server has the user_id too. 
Now its possible to load the user by id, 
check if he is valid (not banned or so),
and can create a new token pair.

The refresh token storage could look like this:

    array(
        // {uuid refresh token} => {user id}
        'd3df3f3df' => 2,
        'e3f3eff3c' => 6,
        'ff3c234aa' => 6, // same user 6 from another device
        // ...
    )

_Your refresh token should be longer ofc_

So one user can have more than one refresh token.
This is good. Because the user could login via phone, tablet, notebook, pc, ... .
 
---
Exampe:

    // Client side: 
    // load refresh token (f.e. from cache which handles the ttl for us)
    $refreshToken = ...
    // use your http client
    $httpClient = ...
    // add the refresh token to the Authorization-header
    $httpClient->setHeader("Authorization: Bearer {$refreshToken}");
    // call the auth server ... (https only PLS)
    $response = $httpClient->get("https://example.com/auth/refresh");
    
    
    // Server side:
    // incoming GET /auth/refresh request
    // get "Authorization: Bearer <token>" see *1 at bottom
    $refreshToken = $this->getAuthorizationBearerToken(
        $this->getRequest()->getHeader('Authorization')
    );
    if ($refreshToken and $this->getCache()->exists($refreshToken)) {
        $userId = $this->getCache()->get($refreshToken);
        $user = $this->findUserById($userId);
        if ($user instanceof User
            and $user->getId()
            and $user->isActive()
            and !$user->isSoftDeleted()
            // and ... what else you need to check ...
        ) {
            // current refresh token is now used (burned) - delete it
            $this->getCache()->delete($refreshToken);
    
            // create new pair of token for user with id $userId
            $accessToken = ...; // your method to create them
            $refreshToken = ...; // your method to create them
    
            // store refresh token
            $cacheKey = $refreshToken;
            $cacheData = $userId;
            $cacheLifetime = ... // your settings ...
            $this->getCache()->save($cacheKey, $cacheData, $cacheLifetime);
    
            $data = [
                'access_token'              => $accessToken,
                'access_token_type'         => 'Bearer',
                'access_token_expires_in'   => ..., // unix timestamp or "Y-m-d H:i:s" (UTC)
                'access_token_expires_at'   => ..., // unix timestamp or "Y-m-d H:i:s" (UTC)
    
                'refresh_token'             => $refreshToken,
                'refresh_token_type'        => 'Bearer',
                'refresh_token_expires_in'  => ..., // unix timestamp or "Y-m-d H:i:s" (UTC)
                'refresh_token_expires_at'  => ..., // unix timestamp or "Y-m-d H:i:s" (UTC)
            ];
    
            // return success with $data
            return ... 201 "Created", $data
        }
    }
    // default return failure (for all cases. dont give out a hint.)
    return ... 401 "Unauthorized"
    
    
    
    *1
    Example:
    /**
     * Returns the authorization bearer token out of the given "Authorization" header field.
     *
     * @param string $authorizationHeader The "Authorization" header field.
     *
     * @return bool|string
     */
    public function getAuthorizationBearerToken($authorizationHeader)
    {
        if (!strlen($authorizationHeader)) {
            return false;
        }
        // parse "Authorization: Bearer <token>"
        $matches = null;
        if (preg_match('/Bearer\s(\S+)/', $authorizationHeader, $matches)
            === 1
            and isset($matches[1])
            and strlen($matches[1])
        ) {
            return $matches[1];
        }
        return false;
    }

_I know i write a lot but i remember searching my a** off when i needed this_

**Comment by usb248** [comment]
Thank you for your long explanations :blush:
But i have others questions.
What king of cache you use (in your script) /advice to use ? (write in database, in a file on server file system ... ?)

I need to manage jwt with mobile app through rest api.
In the situation : (in your [msg](https://github.com/firebase/php-jwt/issues/119#issuecomment-525464922)) (2day later) server checks if refresh token is still valid -> invalid (expired)
Any mobile app (facebook for example) force user to re-login in order to create new token... 🤔  There is any other secure workaround to prevent this to do this like facebook app ?

**Comment by cottton** [comment]
**Storage:**

I cannot recommend a cache. I like redis, but that does not mean that you will like it :D 

You _could_ use a database. But then you would have to search for old rows and delete them 

and then you get id-gaps (if you use AUTO INCREMENT) ... and you have to check if is **still** valid your self by a datetime in your row and ... 


I just took a redis cache, told redis to store the refresh token for n minutes and thats it.

If redis does not give me the token back, then i know:
- user did not had a refresh token
- or user is too late and the refresh token is no more.

BTW: pls dont use files :D

---

**Login:**

Depends ...

Lets say you have users (moderator) that can modify content via the app.

If a moderator must get banned then you should keep the token lifetimes down.

For **example**: 
- access token lifetime: 3 min
- refresh token lifetime: 30 min

If the mod becomes an as#h#le you can immediately block this user on auth server by
- disable his user (he can no more login)
- delete his refresh token(s)

He now has max 3 min to do "damage".

After this time he come in at the auth server with his refresh token and gets a  401 "Unauthorized"
_because you deleted his refresh token server side._

You cannot delete the access token (JWT). So for such cases you want to keep the JTW lifetime low.

_You could use a shared jtw-black-list. I tried to write such a shared system down but never finished it. In short: auth server sends a list of blocked JWT to all other services. So those services know that they have to deny access for token xyz._

---

For the **normal procedure** (user is not banned) the user would 
- have 3 min with access token
- come in with refresh token (less workload than a "real" login)
- starts over with 3 min access token.

**So the refresh token defines when the user has to do the "real" login again.**

_I read about JTW that never expire on mobile devices - i definitely do NOT recommend that :D_
_As long you have the refresh token -control you should be fine. You could set it to 7 days or so._

**Comment by usb248** [comment]
@cottton 
Okey, but i have already a database connection. It's not too "heavy" if i implement an other stockage strategy like redis 🤔 ?

I don't want to force user to re-login. This will frustrate the user compared to other apps. Personnaly, i have any app which force me to re-login (if i reach ttl ? or that mean there is no tll, i guess).

JWT never expire, ok bad idea but about refresh token ? never expire,  it's possible ? :grimacing:

**Comment by cottton** [comment]
**Database**: yea, sure. As long as you remember to check if the refresh token in the db is not already expired.
_Something like `SELECT ... WHERE refresh_token = :refresh_token AND expires_at >= :now ...`_

**Refresh token never expires**: 
possible : yes.
Should do : depends.

**Example 1: shop app (money involved).**

Refresh token ttl is 1 day.
User logs in and receives token pair.
User clicks here and there ... and the token gets refreshed ... .
Now user is away for 2 hours.
User is back -- access token is expired, refresh token is used to get a new pair. _All fine._

Now user is away for 3 days.
User starts app and has to login.

From the security point of view i would say this is good.
If the user lost his phone then an "attacker" may not gain access, because the refresh token has been expired.

**Example 2: weather app (no money involved).**

Refresh token ttl is 365 days _(or more)_.
User logs in and receives token pair
...
User is away for 3 days.
User starts app -- access token is expired, refresh token is used to get a new pair. _All fine._

This should be ok. I guess a lot of apps do that. 

---

So it depends. As long you can delete the users refresh token you should be fine.
_F.e. if he lost his phone and logs in via PC to log out "other devices". Which you could build with that "system". Thats the point where a database makes more sense than simple cache :)_

**Comment by usb248** [comment]
Thanks for your explanations @cottton ! I don't understand a few lines of your code .. :
```
            'refresh_token'             => $refreshToken,
            'refresh_token_type'        => 'Bearer', // Why Bearer, it's not specific to JWT ? it should be not a uniqid/uuid string ?
            'refresh_token_expires_in'  => ..., // unix timestamp or "Y-m-d H:i:s" (UTC) => not rather a time expressed in seconds. Ex: 3600 (for one hour?)
```

**Comment by cottton** [comment]
**Why** Bearer:

I actually dont know _exactly_ why we should use `Authorization: Bearer <token>` header.
I searched and read about how to send them _(access- and refresh token)_ and i think most services expect it like that. 

See _"How do JSON Web Tokens work?"_ at https://jwt.io/introduction/

> Whenever the user wants to access a protected route or resource, the user agent should send the JWT, typically in the Authorization header using the Bearer schema. The content of the header should look like the following:
`Authorization: Bearer <token>`

I also searched for auth server response examples.
I found the `..._token_type` which indicates the `Bearer` header type.
So its possible to read in the response how the auth server expects the token to be send in.

---

`_expires_in` indeed should be in seconds. My bad :D _(fixing it in my response above)_

**Comment by fvgtekken** [comment]
Cotton thank you for the  detailed explanation, it helped me a lot.

**Comment by mosi2142** [comment]
@cottton thank you for your explanation it helped me a lot,
i just have a question and im really confused about it, i really appreciate if you can help me with it
my question is :
if lets say a hacker somehow get the access token and refresh token of the user 
how can i know that ? 
i mean if the hacker get the user token then he is no different with the actual user right ?
so is there any suggestion that what should i do, to know the difference between the user and a hacker that stole the user token

**Comment by katowulf** [comment]
Access to the refresh and access tokens would imply access to the physical device or successful execution of some sort of man-in-the-middle. So there would be no way to differentiate.

**Comment by mosi2142** [comment]
> 
> 
> Access to the refresh and access tokens would imply access to the physical device or successful execution of some sort of man-in-the-middle. So there would be no way to differentiate.

not necessarily should access the physical device in order to steal the user token,
im sure there is always way to steal token without accessing the physical device such as Xss attack or Listening or etc...

**Comment by cottton** [comment]
If somebody gets the token 
then its the same as the attacker got access to the login.

The client responsible to store the token.
Most important is the refresh token, since you can create more|new access token with the refresh token.
The access token is (in best case) expired in some min.


> so is there any suggestion that what should i do, to know the difference between the user and a hacker that stole the user token

You cannot know, as @katowulf said.
What you can do is provide the user a logout.
Logout means: 
- user calls logout request at auth server. (Must send access token with this request. Refresh token would be valid too tho.)
- auth server checks if the access-|refresh- token is valid (token not expired, and user is valid (not disabled, deleted, ...))
- auth server now deletes token of the user (which should be refresh token only, since the auth server does not store access token)
- user is logged out

**Comment by mosi2142** [comment]
> 
> 
> If somebody gets the token
> then its the same as the attacker got access to the login.
> 
> The client responsible to store the token.
> Most important is the refresh token, since you can create more|new access token with the refresh token.
> The access token is (in best case) expired in some min.
> 
> > so is there any suggestion that what should i do, to know the difference between the user and a hacker that stole the user token
> 
> You cannot know, as @katowulf said.
> What you can do is provide the user a logout.
> Logout means:
> 
>     * user calls logout request at auth server. (Must send access token with this request. Refresh token would be valid too tho.)
> 
>     * auth server checks if the access-|refresh- token is valid (token not expired, and user is valid (not disabled, deleted, ...))
> 
>     * auth server now deletes token of the user (which should be refresh token only, since the auth server does not store access token)
> 
>     * user is logged out

Thank you for replying i really appreciate it.
just one thing to add up,
is it okay to hash the refresh token and then store it to db ?

**Comment by cottton** [comment]
> so is there any suggestion that what should i do, to know the difference between the user and a hacker that stole the user token

You cannot know by the token it self.
Its the same like somebody got the username and pw of a user.
You COULD add more security like location limitations|checks, 2-auth, ... . But that is on top of JWT, so ... .


> is it okay to hash the refresh token and then store it to db ?

If you mean with "hash" to store it like a pw _(PHP `password_hash()`)_ 
and then compare hash vs hash _(with PHP `password_verify()`)_
then ... hm, kind of yes.
Didnt thought about that. But **makes sense**, since you can create an access token with the refresh token.
_And you get new refresh token on each refresh request - so you could keep this access open for ever._

So yes, you **should**, store the refresh token like a password - hashed. 
And handle it like a pw on refresh.

The plain refresh token in the db could lead to serious security problems.
Somebody reads the db (leak, ...) then he got the real refresh tokens - which mean he can login as any user (as long the refresh token is not out of date).
_This would be the same like somebody stored plain text passwords in the db._

**Yes, handle the refresh token like a plain text password.**

**Comment by bshaffer** [comment]
This is a great discussion but I'm closing this issue as there's nothing actionable here for this library.
