### ISSUE TITLE
Missing decode example

### ISSUE THREAD

**Issue by gbittmann** [firebase/php-jwt#144]
There doesn't seem to be an example of how to use this library to decode a jwt provided from firebase authentication.

**Comment by gbittmann** [comment]
`<?php

// Reference: https://firebase.google.com/docs/auth/admin/verify-id-tokens

require_once "vendor/autoload.php";

use \Firebase\JWT\JWT;

try {
    // Token to decode
    $jwt = 'your_token_here';

    // Get public keys from URL as an array
    $publicKeyURL = 'https://www.googleapis.com/robot/v1/metadata/x509/securetoken@system.gserviceaccount.com';
    $key = json_decode(file_get_contents($publicKeyURL), true);

    // RS256
    $decoded = JWT::decode($jwt, $key, array('RS256'));

    print_r($decoded);
}
catch (Exception $e) {
    echo $e->getMessage();
}`

**Comment by Akshata-Unocoin** [comment]
"Algorithm not allowed" iam getting this error after excuting the above example

**Comment by bshaffer** [comment]
This is because the algorithm declared in the `$jwt` header is not in the allowed algorithms you're passing in, i.e. it's not `RS256`.  See [here](https://github.com/firebase/php-jwt/blob/master/src/JWT.php#L97).

To see what your JWT's header is, do this:

```php
$tks = explode('.', $jwt);       
list($headb64, $bodyb64, $cryptob64) = $tks;
$header = \Firebase\JWT\JWT::jsonDecode(Firebase\JWT\JWT::urlsafeB64Decode($headb64));
var_dump($header->alg);
```

**Comment by Akshata-Unocoin** [comment]
WIll you please send me the proper example for deocde.

**Comment by myGIT843960877** [comment]
Please make sure your algorithm  in right reocrd

**Comment by Akshata-Unocoin** [comment]
Please make sure your algorithm in right reocrd - you mean updated one?

**Comment by myGIT843960877** [comment]
Here code in my program
` global $sys_setting;
        $jwt_conf = $sys_setting['jwt'];
        if(empty($jwt_conf['alg']))
        {
            $jwt_conf['alg'] = 'RS256';
        }
        if(in_array($jwt_conf['alg'], array('RS256','RS384','RS512')) == 0)
        {
            $ssl_conf = $sys_setting['ssl'];
            if(empty($ssl_conf['pri_key_path']))
            {
                throw new Exception('please config your ssl cert!');
            }
            if(empty($ssl_conf['pub_key_path']))
            {
                throw new Exception('please config your ssl cert!') ;
            }
            Rsa::loadSslKey();
            $jwt_conf['key'] = Rsa::$pub_key_content;
        }
        if(empty($jwt_conf['leeway']))
        {
            fir_jwt::$leeway = 180;
        }
        fir_jwt::$leeway = $jwt_conf['leeway'];
        return fir_jwt::decode($token, $jwt_conf['key'],  array($jwt_conf['alg'])  );`
You can copy this

**Comment by Akshata-Unocoin** [comment]
See i need proper decode method.....
when i execute this

"<?php

// Reference: https://firebase.google.com/docs/auth/admin/verify-id-tokens

require_once "vendor/autoload.php";

use \Firebase\JWT\JWT;

try {
    // Token to decode
    $jwt = 'your_token_here';

    // Get public keys from URL as an array
    $publicKeyURL = 'https://www.googleapis.com/robot/v1/metadata/x509/securetoken@system.gserviceaccount.com';
    $key = json_decode(file_get_contents($publicKeyURL), true);

    // RS256
    $decoded = JWT::decode($jwt, $key, array('RS256'));

    print_r($decoded);
}
catch (Exception $e) {
    echo $e->getMessage();
}

"

Iam getting algorith not allowed error

when i execute this
<?php
use \Firebase\JWT\JWT;
$publicKey = <<<EOD
-----BEGIN PUBLIC KEY-----
MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQC8kGa1pSjbSYZVebtTRBLxBz5H
4i2p/llLCrEeQhta5kaQu/RnvuER4W8oDH3+3iuIYW4VQAzyqFpwuzjkDI+17t5t
0tyazyZ8JXw+KgXTxldMPEL95+qVhgXvwtihXC1c5oGbRlEDvDF6Sa53rcFVsYJ4
ehde/zUxo6UvS7UrBQIDAQAB
-----END PUBLIC KEY-----
EOD;

$jwt = "ergh......";

$decoded = JWT::decode($jwt, $publicKey, array('RS256'));

/*
 NOTE: This will now be an object instead of an associative array. To get
 an associative array, you will need to cast it as such:
*/

$decoded_array = (array) $decoded;
echo "Decode:\n" . print_r($decoded_array, true) . "\n";
?>

i am getting internal server errror in jWT::decode
