### ISSUE TITLE
where to store user info in sub or aud

### ISSUE THREAD

**Issue by pramodwerea** [firebase/php-jwt#169]
Is it a correct way to set the user info(id, name) in the **aud** payload field and read the **aud** field after de-code to get the user? Because while reading through JWT articles seems user info is mainly saved into "**sub**" subject field.

**Comment by HenryNe** [comment]
You can simply add your fields id and/or name to the jwt. There is no problem with your own field names, as long you not use _Registered Claim Names_ (rfc7519). Of curse, you can use aud for it, because aud is interpreted by application only.
For me, I use sub for what the user will do. For example sub="login", name="me".

**Comment by pramodwerea** [comment]
@HenryNe thanks for the information!
