### ISSUE TITLE
this repo is not showing up in search

### ISSUE THREAD

**Issue by ganganimaulik** [firebase/php-jwt#172]
I search for **jwt** and sort by **most stars**

https://github.com/search?o=desc&q=jwt&s=stars&type=Repositories&utf8=%E2%9C%93

can't see it. I think something is wrong, either with github or some settings in this repo.

**Comment by saranshdhingra** [comment]
I think by default the search results don't return forked repo results.
In order to do so, you need to add `fork:true` in your search query. Once you do so, this repo should be visible.
Here is a [link](https://github.com/search?q=jwt+fork%3Atrue&type=repositories&s=stars&o=desc&p=2).

Thanks for the question :)
