### ISSUE TITLE
why use 'nbf' and 'leeway' at the same time?

### ISSUE THREAD

**Issue by williamqian** [firebase/php-jwt#200]
I'm a little confused

**Comment by carmanchris31** [comment]
Leeway lets you account for small discrepancies in different clocks. So if you tell me my coupon is not valid until 4:50pm and my watch says it's 4:59pm I could give you some leeway and let you use it because my watch might just be slightly off. That's why it's recommended to not be more than ~1-2 minutes.

**Comment by williamqian** [comment]
I get it,thanks very much。
