### ISSUE TITLE
What is the use of "iss" and "aud" in your example?

### ISSUE THREAD

**Issue by carlo-fontanos** [firebase/php-jwt#211]
I saw these 2 in your example: 
```
"iss" => "http://example.org",
"aud" => "http://example.com",
```
I don't see any check for these parameters under **vendor\firebase\php-jwt\src\JWT.php** 

What is it for? how do I use it in a real word scenario?

I have a react app running on the url: http://localhost/test:3000
And a php api server running on the url: http://localhost/test

My react app fetches data from php api server, so is it correct to set **iss** and **aud** like this: 

"iss" => "http://localhost/test:3000",
"aud" => "http://localhost/test",

Is this the intended usage?

**Comment by Yamakasi** [comment]
Hi,

It's RFC documented, look here: https://tools.ietf.org/html/rfc7519#section-4.1

**Comment by fernando-ayon** [comment]
I believe that what @Yamakasi tried to point out with the provided link is that both 'iss' & 'aud' claims are application specific, so it is up to you to handle them if or however you deem necessary.

These claims are also called 'public' or 'reserved' claims, because they are defined in the RFC and their values should be consistent with the definitions provided in the standard.a

**Comment by ajupazhamayil** [comment]
Thank you for the discussion.
