### ISSUE TITLE
Encode incorrect with sequential arrays

### ISSUE THREAD

**Issue by MvonNeumann** [firebase/php-jwt#259]
Encoding non-associative arrays will produce results that are not in proper JSON format. The result could not be decoded for example with PyJWT's ```jwt.decode``` function in Python 3.
The first line of ```jsonEncode``` function:
```
public static function jsonEncode($input){
  $json = json_encode($input);
...
```
will produce ```["item1","item2","item3"]``` from sequential arrays like ```array("item1", "item2", "item3")```, instead of the proper ```{"0":"item1","1":"item2","2":"item3"}``` format.

The code should be updated as:
```
public static function jsonEncode($input){
  $json = json_encode($input, JSON_FORCE_OBJECT);
...
```
to work with both sequential and associative arrays. It has been tested and seems to work fine.

**Comment by Krisell** [comment]
`["item1","item2","item3"]` is definitely proper JSON, see https://www.json.org/

**Comment by bshaffer** [comment]
I went through the [JWT spec](https://tools.ietf.org/html/rfc7519) and found nothing regarding sequential arrays. Where do you see that these should be encoded as objects?

**Comment by NiMeDia** [comment]
The JWT spec talks only about "JSON Objects" so maybe the token must always be an object to match the spec? (I don't really know wheter PyJWT is right in this case). I think that PyJWT only supports decoding from an object structure, because in python there is a difference between arrays and dicts and array support is not needed primarily if you encode and decode with the same library. 

Can anyone try to decode array tokens with another library to ensure PyJWT is right in this point?

If they are right and tokens have to be objects, we should consider to use the JSON_FORCE_OBJECT flag.

**Comment by lindelius** [comment]
The RFC defines claim values as 
>  The value portion of a claim representation. A Claim Value can be any JSON value.

It’s pretty clear that arrays are allowed.

**Comment by NiMeDia** [comment]
OK, in this case it's an issue of PyJWT rather than PHP-JWT. @MvonNeumann could you redirect your issue to PyJWT? (Would be nice if you link it here for anyone who has the same problem)

**Comment by bshaffer** [comment]
I filed an issue against the PyJWT repo here: https://github.com/jpadilla/pyjwt/issues/476

Please provide steps to reproduce, @MvonNeumann 

All further discussion can be continued there, as there is no issue (AFAIK) with this library.

Thanks!

**Comment by MvonNeumann** [comment]
Yes after further investigation I also have to agree that the problem is in the PyJWT and not the PHP-JWT. Sorry for the issue, and thank you for your time!
