### ISSUE TITLE
Failed Decoding with Error Key may not be empty

### ISSUE THREAD

**Issue by ikhbalfuady** [firebase/php-jwt#296]
Iam using this plugin in lumen, and testing in xampp

every 3, 4 or 6 not even sure, I make a request, there is always an error "Key may not be empty", this error always appears if I do not do "php serve" or I immediately access the public folder with an example url

http://localhost/core-api/public/

and when I serve, the error does not appear, is "serve" a requirement?

**Comment by ali-sharafi** [comment]
This happened for me too. :(

**Comment by bshaffer** [comment]
You can see this error is thrown on this line:

https://github.com/firebase/php-jwt/blob/48b0210c51718d682e53210c24d25c5a10a2299b/src/JWT.php#L104-L106

So, for some reason, an empty second argument is being passed `JWT::decode`.

This issue is happening outside of this library, so there's nothing actionable our end. I would suggest looking at the calling function and seeing what could cause that second parameter to be empty.
