### ISSUE TITLE
I suggest that JWK::parseKey() be made public

### ISSUE THREAD

**Issue by csev** [firebase/php-jwt#319]
There are situations where we want to parse a key that is not always part of a keyset.  Perhaps we stored the key in session or in a database - or perhaps in a unit test.

**Comment by bshaffer** [comment]
@csev You can always call `JWT::parseKeySet(['keys' => $key']);`, so I don't understand why it is necessary to make `parseKey` public.

**Comment by csev** [comment]
Thanks - that makes a lot of sense.   It is good enough for me.

**Comment by simonknittel** [comment]
I've just stumbled upon an implementation in which the JWT doesn't contain a kid. Therefore parseKeySet wasn't able to find the correct key. Being able to directly call parseKey would help here.

**Comment by kamazee** [comment]
Same here.
To get a single key, `JWT::parseKeySet(['keys' => [getkey($id)]])[$id]` is required instead of just `JWT::parseKey(getKey($id));` (where `getKey($id)` is a function that returns a key by its ID that is passed in a JWT header)
While the former is indeed possible, it's clearly quite a mental roundtrip while the latter shows the intent pretty clearly.

@bshaffer , any chance to reconsider? 🙄

**Comment by bshaffer** [comment]
I can't see an issue with making it public if there's a use-case for it
