### ISSUE TITLE
 a bug

### ISSUE THREAD

**Issue by guohanmeng** [firebase/php-jwt#345]
![image](https://user-images.githubusercontent.com/10897119/123393335-8f5bbd00-d5d0-11eb-92bb-6405b7533ea7.png)

![image](https://user-images.githubusercontent.com/10897119/123393233-78b56600-d5d0-11eb-8147-63353110a49d.png)
![image](https://user-images.githubusercontent.com/10897119/123393467-b74b2080-d5d0-11eb-9975-bff2a475d842.png)

我现在获取的$errno 是 4 找不到对应的 messages ，数组key和获取的errno 不对等

**Comment by Krisell** [comment]
You have to rewrite this in english for the maintainers and us (users) to understand your problem.

If you think there is a bug in the code, you should write clear steps to reproduce this or (even better) a failing test.

If you mean that you hit `JSON_ERROR_DEPTH`, the problem is with your data and not this package.
