### ISSUE TITLE
Makes the 'typ' header truly optionnal

### ISSUE THREAD

**Issue by olinox14** [firebase/php-jwt#418]
[JWT specifications](https://self-issued.info/docs/draft-ietf-oauth-json-web-token.html#typHdrDef) statues that the 'typ' header is optional. However, the `JWT::encode` method automatically add the header, and doesn't provide any option to remove it.

I'm currently stuck because, for an unknown reason, the Mercure hub (written in GO and using [jwt-go](https://pkg.go.dev/github.com/dgrijalva/jwt-go) to parse the jwt) throw an 'invalid signature' error whenever the 'typ' header is added. I submitted an issue on their github too, but I still think it could be useful to be able to completely override the header of a JWT.

**Comment by bshaffer** [comment]
I am not sure I understand your ask. Just because it's optional in the JWT spec doesn't mean this library shouldn't always set it. Unless there is a specific bug with this library you'd like to report, there's nothing I can do here.

**Comment by olinox14** [comment]
I encountered a difficult problem with mercure, and the only difference I found at this time between the working update and the non-working one was the header. After some hours, I finally understood that the problem was caused by something else (involving some symfony cache not being correctly cleared).

Fact is, I would have gained some time if I have been able to setup the header of the JWT, and having total control on it, I would have been able to innocent the 'typ' header quicker. It's not a bug, but this could be a feature, and it would be coherent with the specs.

**Comment by bshaffer** [comment]
I don't disagree that we could open up options for more header control. We do offer the `$head` parameter, which cannot be used to override the pre-populated values of `typ` and `alg` (for security reasons). 

If the reason you needed it was for debugging purposes, I do not think it merits a change to the library (which could potentially open up a security hole). However, we are always open to suggestions! That's what Open Source is all about! 

I'm closing this because it's too broad, but please create a new issue with a more specific ask if you have an idea of how to implement better header control without sacrificing security.

**Comment by bshaffer** [comment]
The `"typ"` header is now able to be overwritten using the `$head` parameter as of [v6.10.0](https://github.com/firebase/php-jwt/releases/tag/v6.10.0). Note that supplying `"alg"` in the `$head` parameter will still not have an effect, as the required `$alg` parameter takes precedence.
