### ISSUE TITLE
Return value of JWT::getKey() must be an instance of Firebase\JWT\Key

### ISSUE THREAD

**Issue by Summersyard** [firebase/php-jwt#432]
We encounter this bug with the current version 6.2.0:
![SSO error php-jwt-6](https://user-images.githubusercontent.com/106656765/171371383-ee17eac8-9023-4c27-813b-78ffd1f98fe5.png)

At first glance one could think the problem lies within Thenetworg/oauth2-azure (I have postet the issue there as well). However, the stack trace looks like the firebase/php-jwt code internally returns an invalid (string) data type.

**Comment by mahmoud-birdsol** [comment]
+1

**Comment by ganey** [comment]
When I upgraded locally to v6, i had to wrap my key strings in a `new Key($key, $algo)` call.

this package doesn't validate that the array of keys you pass in are instances of `Firebase\JWT\Key`, maybe [this method ](https://github.com/TheNetworg/oauth2-azure/blob/56e0776776476da0b2de8cb7c201bfe7dec7aee1/src/Provider/Azure.php#L336)in the oauth2-azure package isn't returning them as an array of `Firebase\JWT\Key`?

**Comment by spackmat** [comment]
I took a look into the affected Method `Firebase\JWT\JWT::getKey()` and in line 439 it does in fact return the key as a string instead of a `Key` object: `return $keyOrKeyArray[$kid]`, where `$keyOrKeyArray` is an array of Keys according to the `@param` annotation. But the method does not check that, so the problem seems to be in `Thenetworg/oauth2-azure`, where the keys are given as an array of string keys. So I think @ganey is correct here. The issue mentioned in the first post is this one: https://github.com/TheNetworg/oauth2-azure/issues/161

**Comment by grafickepracecom** [comment]
As @spackmat stated, this is not a bug in php-jwt. However, it is IMHO quite hostile to change (break) API in minor version and not maintain backward compatibility. Could you add backward compatibility for v6.x and/or renumber this version as v7.0?

**Comment by spackmat** [comment]
@grafickepracecom the breaking change came with v6.0.0 and in that version there was also a check with a helpful error message within a `UnexpectedValueException`. That check was removed with 6.1.0. Why was this exception removed? I don't know, but IMHO the problem is completely in `Thenetworg/oauth2-azure` that recently updated `firebase/php-jwt` to v6 and did not implement that breaking change.

**Comment by bshaffer** [comment]
The check was removed because I preferred to use PHP's return typehints rather than throwing my own exceptions. However, I can understand that the exception `Return value of JWT::getKey must be an instance of Firebase\JWT\Key` is not as helpful an error message as `$keyOrKeyArray must be an instance of Firebase\JWT\Key key or an array of Firebase\JWT\Key keys`.

I could add the old error message back, but at this point it may be more trouble than it's worth.

**Comment by spackmat** [comment]
Since there was a recent breaking change in the API at a point that is used by other projects regulary, bringing back the helpful error message could reduce the questions asked here. So maybe it would be a good idea. To make it clear that the problem is introduced by not updated code other codebases using the JWT, the message could also give the information that this was changed in version 6.0 and the code using the new version has to be updated. At least this would be a nice service to avoid irritation.

**Comment by chennien** [comment]
+1

**Comment by tuupola** [comment]
Also having a CHANGELOG file would help a lot.
