### ISSUE TITLE
Can put it in Controller ? 

### ISSUE THREAD

**Issue by ykenny** [firebase/php-jwt#44]
I want to build secure api application consult of http://www.toptal.com/web/cookie-free-authentication-with-json-web-tokens-an-example-in-laravel-and-angularjs

As far as  work great in my routes.php, but when i move this code in my controller
   if ( ! $token = JWTAuth::attempt($credentials)) {
       return Response::json(false, HttpResponse::HTTP_UNAUTHORIZED);
   }

it throw exception like this 
Non-static method Tymon\JWTAuth\JWTAuth::attempt() should not be called statically, assuming $this from incompatible context

If you know what is happened , can you tell me what can i do ?
Should i put  all the code in my routes?
thanks!

**Comment by robertdimarco** [comment]
Apologies for the delayed response here. Without more code or a reproducible case, it would be hard to break down what the issue is here. I would recommend using StackOverflow for more help about what your code is doing, and feel free to follow-up here if you think you've run into a bug or missing feature.
