### ISSUE TITLE
Missing Exception file causes decode failure

### ISSUE THREAD

**Issue by rocanion** [firebase/php-jwt#64]
Apparently there is a missing DomainException.php file. The decode function fails because the DomainException class is not defined.

**Comment by rocanion** [comment]
By the way, the fix is as easy as copying one of the existing exception class files with the proper naming.

**Comment by robertdimarco** [comment]
@rocanion Which version of PHP are you using?

**Comment by lcabral37** [comment]
Just because I have nothing better to do...
@rocanion http://php.net/manual/pl/class.domainexception.php
This means you should have DomainException as part of the php from 5.1.0
Having said this, if you are using some version as early as that, you should probably consider upgrading your PHP version if possible.

**Comment by rocanion** [comment]
I am using php 5.4.x

So this leaves me puzzled as to why I am seeing this error if the exception
is supposed to already be defined in my version of php.

Thanks for the replies!

Dan

**Comment by yash30201** [comment]
Apparently there have been a lot of library changes and upgrades from the time this issue was raised. Please try with the updated version and reopen if this issue still persists.
