### ISSUE TITLE
Feature request - decode without verifcation

### ISSUE THREAD

**Issue by amnah** [firebase/php-jwt#68]
Would be nice to be able to decode the jwt without needing to verify the signature. 

Eg, if you need to do additional processing when the jwt is expired.

Something like [this](https://github.com/psecio/jwt/blob/master/src/Psecio/Jwt/Jwt.php#L148):

`public function decode($jwt, $verify = true)`

**Comment by lcabral37** [comment]
I'm not the maintainer of this project but my view regarding this is that the library is tying to implement a standard which has specific rules regarding its behavior and the library should not deviate from the standard. The result of that is potential security vulnerabilities.

Now if your only concern is expired JWT, a while back I contributed with a patch to add a leeway, mostly to handle the scenario when the time of the server that signed does not match the decoding server. So the specification allows the JWT protocol to account for a few minutes leeway. You can use it by setting 
```php
JWT::$leeway = 60; // 1 minute
```
If that is not your problem but instead  you care nothing about the standard and only care about reading the content of the JWT token, without any concern about who sign it you could read the code, figure out what it is doing and within a couple of minutes you would find something like this
```php
$tks = explodee('.', $jwt);
list($headb64, $bodyb64, $cryptob64) = $tks;
$payload = JWT::jsonDecode(JWT::urlsafeB64Decode($bodyb64))
```
An there you have your invalidated payload. But make to be aware this might be a huge security flaw if you are using this in a service.

**Comment by WilliamMayor** [comment]
This would be a useful feature for me.

I'd like to use a key per user, not a global key. I'd also like to avoid hitting the DB for every decode. What I thought I'd do is this:

```
$encoded = JWT::encode($payload, $key=hash("sha256", "$userId-$globalSalt"))
```

But now to decode I need to know the user's ID:

```
$payload = JWT::decode($encoded, $verify=false)
$payload = JWT:decode($encoded, $key=hash("sha256", $payload["sub"] . "-$globalSalt"))
```

Of course I can use the above workaround. I just thought I'd give some reasoning behind this feature request beyond "I care nothing about the standard".

**Comment by tuupola** [comment]
JWT payload is just base64 decoded data. You can extract the payload with simple PHP.

```php
$token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWV9.TJVA95OrM7E2cBab30RMHrHDcEfxjoYZgeFONFh7HgQ";

list($header, $payload, $signature) = explode (".", $token);

print base64_decode($payload);
```

**Comment by WilliamMayor** [comment]
Yeah, I get that you can do it without using the library. I suppose my point was that the feature request is a valid one and maybe should be worth considering.

The JSON decoding in the library isn't quite as trivial as your example. There's stuff in there about checking for large ints and PHP versions. It's shame to lose these optimisations (and any future ones).

**Comment by TangoMan75** [comment]
I understand that an expired tokens should return an invalid status. But I don't see where the specs doesn't allow invalid tokens to return payload...

**Comment by mewejo** [comment]
This would be very handy to have, to say find the users ID from the payload, to then fetch their token to validate the JWT against. I'll extract them manually for now, but it's a shame to miss out on extra validation this library already provides.

**Comment by benzittlau** [comment]
I believe that one of the great *advantages* of JWT is the ability for clients to inspect the contents of the payload without needing the private key.  This allows for certain "dumb clients" that don't know the private key (maybe they're in an insecure environment, or it's behind a reverse proxy layer that has already authenticated the token) to be able to inspect the contents.  It's definitely true you can avoid this library and do manual extraction of the payload, but it feels to me that it would be within the reasonable scope of a JWT library to support extracting the payload independent from verifying the token.

**Comment by lindelius** [comment]
Due to the lack of this feature, along with the fact that this library isn’t being maintained, I decided to write my own a while back. So, if you’re looking for this feature, feel free to have a look at [my library](https://github.com/lindelius/php-jwt).

**Comment by kdubuc** [comment]
I agree with the feature request.

In my case, I need to extract "iss" claim to fetch signing keys. So, I must copy/past some JWT.php code to decode payload, and, after that, re-decode with JWT::decode to verify signature, and check nbf / exp .... It works, but, it's not very pretty ...

We can easily make "verify" optional, the question is how ?

I can propose 2 solutions :

1. In https://github.com/firebase/php-jwt/blob/master/src/JWT.php#L79, if $key and $allowed_algs are empty, make verify signature optional.
2. Add a new static function JWT::decodeWithoutVerifySignature($jwt). Move JWT validate / decode code in that function, and reuse it in JWT::decode.

What do you think @bshaffer ?

I can work on a PR if you are interested.

**Comment by bshaffer** [comment]
I do not think we want to encourage an easy workaround to bypass JWT validation. This could really result in abuse of this code base and allow for security breaches.

If somebody can provide me a trusted source for why pulling values from the JWT header or payload and using them prior to validation is secure, I'll reconsider.

**Comment by mewejo** [comment]
The use case I had for it was to find the users ID from the payload, to then fetch their token to validate the JWT against. The same could be necessary for the issuer too.

Not including it in the library forces people to implement their own solutions, which could themselves be a problem.

**Comment by kdubuc** [comment]
There is a difference with encryption and signature : If a JWT is signed, but not encrypted, the contents is clearly open : anyone can read payload / header / signature.
If a JWT is signed, the signature is used to verify if the contents was not altered, not to control if the contents can be read or not.

**Comment by indreksiitan** [comment]
My usecase - I have a REST API that uses JWT token to authenticate. I call the /authenticate method with credentials and the only thing I receive back is the token, which should be used for subsequent API calls. I don't have the key and I don't specifically need the key.

However, the token is valid for some time, as expressed by the "exp" parameter in the payload. I currently decode this manually in order to understand for how long I can cache and use this token without re-authenticating, but thought it would be "nicer" to use the JWT library for this what I was already using for other purposes, such as encoding tokens for other API-s. 

But in the process of that I ran into this key problem that led me to this issue.

**Comment by leongrdic** [comment]
This would be a really useful feature in a situation when JWTs are signed with a secret concatenated with e.g. a user ID that's contained in the payload.

**Comment by bshaffer** [comment]
> If a JWT is signed, the signature is used to verify if the contents was not altered, not to control if the contents can be read or not.

This is true, but my point is we cannot _trust_ the contents _until_ the JWT is verified, and the request here is to decode without verification. 

>  I currently decode this manually in order to understand for how long I can cache and use this token 

This is a fair use-case. I've proposed solutions such as `JWT::decodeExp`, to handle _specific_ values which should be able to be read without verification. Even with this I'd want to do some digging to make sure it's considered okay.

> This would be a really useful feature in a situation when JWTs are signed with a secret concatenated with e.g. a user ID that's contained in the payload.

This sounds very interesting, but I don't really understand fully what you mean, or what the implications would be. Please provide a more specific use-case (in a separate issue, would be preferable) and we can discuss a solution there.

In summary, I don't want this library to encourage the reading of unverified headers / payloads. If you need this in your application, and you feel okay taking the risk, it is quite easy to write the code to do so. I have yet to read anything that says this is okay to do, but if there is some IETF documentation that says otherwise, I'm certainly willing to change my mind.

**Comment by leongrdic** [comment]
here's my specific use case:

a user wants to change their email. backend generates a JWT that contains user id, new (pending) email address and expire time in payload. JWT is signed with a (backend-level) secret concatenated to the users old email address. 
this JWT is then sent within a link to the new email address, and the user is expected to click on it to verify their new email address.
when the user clicks the link, we need to be able to read the users id from JWT payload so we could find the users current (soon-to-be old) email address which is again concatenated with secret to verify JWT.

this in practice invalidates a JWT when the user changes their email to a third address (neither the old nor the new one) which is actually expected behavior - we don't want other email verification links to be vaild after one has been used.


a different approach would be to keep a hash of the users current email address in the payload so it can be compared later after decoding and verifying the payload which basically increases size of the whole JWT but provides no more or less security.

i'd prefer to be able to do the first approach, and ideally use a library for each step.

**Comment by kdubuc** [comment]
> In summary, I don't want this library to encourage the reading of unverified headers / payloads.

Fair enough !

> it's INCREDIBLY easy to

Indeed, here is a simple snippet, with using the library, to decode JWT's payload  :

```php
[, $payload_b64] = explode('.', $jwt);
$payload = JWT::jsonDecode(JWT::urlsafeB64Decode($payload_b64));
```

**Comment by bshaffer** [comment]
Closing this issue as we have no plans to support this. Thank you for your solution, @kdubuc!
