### ISSUE TITLE
Is this codebase still maintained?

### ISSUE THREAD

**Issue by josephmcdermott** [firebase/php-jwt#94]
A few PR's building up but no commits or merges to main project for a while? Just wondering whether I stop waiting and use my own fork. Cheers, Joseph

**Comment by swestcott** [comment]
+1 interested in the response

**Comment by stdinh** [comment]
+1

**Comment by vthorsell** [comment]
+1

**Comment by thorsten** [comment]
+1

**Comment by thorsten** [comment]
https://twitter.com/_jwngr/status/736398179445280770

**Comment by robertdimarco** [comment]
Hi folks!

As you've all noticed, we haven't been able to give this project much love lately, primarily because we've been hard at work building all of those new Firebase products and features that recently launched at Google I/O (*see* https://firebase.googleblog.com/2016/05/firebase-expands-to-become-unified-app-platform.html).

That said, I'm hoping I can get through all of the pull requests that have been opened up here and cut a release since you no doubt want all of these great updates. Bear with me, and I'll do my best to carve out a little bit of time to make this happen over the next week or so. Thank you -

Rob
